### ISSUE TITLE
Improve travis config

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-indirect-taxation#106]
Travis build [fails]  (https://travis-ci.org/benjello/openfisca-france-indirect-taxation/builds/103577210)
because it needs newer pandas version. 
@cbenz: could'nt we use something like [this] (https://github.com/geopandas/geopandas/blob/test/pandas-0.17/.travis.yml) ?

**Comment by cbenz** [comment]
I'm working on Travis for numpy 1.10 on https://github.com/openfisca/openfisca-france/issues/416 too

**Comment by cbenz** [comment]
I'm exploring Miniconda too

**Comment by benjello** [comment]
Fixed
