### ISSUE TITLE
Traduire les exemples .py en notebook

### ISSUE THREAD

**Issue by MarionIPP** [openfisca/openfisca-france-indirect-taxation#109]
Dans le dossier exemples, convertir les exemples .py en notebook. Certains exemples peuvent être groupés dans le même notebook (car font des choses similaires, mais sur différentes périodes par exemple).

**Comment by benjello** [comment]
Existe déjà #88
N'hésite pas à en refermer une et à compléter l'autre.

**Comment by benjello** [comment]
duplicate
