### ISSUE TITLE
Migrer les csv en csv standard

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-indirect-taxation#131]
C'est à dire sans sep = ';'.
Le but est qu'il soit visibles dans github.
Il est également possible de virer ceux qui ne servent plus ...

**Comment by benjello** [comment]
@thomasdouenne : comme c'est souvent toi qui les crée avec un séparateur ';',  pourrais-tu checker rapidement cela que l'on ferme cette issue. Merci.

**Comment by thomasdouenne** [comment]
J'en ai changé un certain nombre, et j'ai gardé ceux pour lesquels c'était nécessaire : par exemple, ceux pour lesquels ',' représente la décimale du nombre.

**Comment by benjello** [comment]
Tu peux choisir le marqueur d'un nombre decimal dans `to_csv` et `read_csv` en utilisant le mot-clé `decimal = '.'`.

**Comment by thomasdouenne** [comment]
D'accord. Par contre il en reste pour lesquels ; et , sont définis lorsqu'on les importe (ex : prix des biens d'après l'Insee)

**Comment by benjello** [comment]
On ne modifie pas les sources brutes.

**Comment by benjello** [comment]
@thomasdouenne puis-je fermer ce ticket ?

**Comment by thomasdouenne** [comment]
Oui tu peux
