### ISSUE TITLE
What is this sourcp variable 

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-indirect-taxation#147]
@thomasdouenne : [what is this variable for](https://github.com/thomasdouenne/openfisca-france-indirect-taxation/blob/energie-migration/openfisca_france_indirect_taxation/build_survey_data/step_3_homogeneisation_caracteristiques_menages.py#L281)
Why do you need a separate dataframe ?

**Comment by thomasdouenne** [comment]
sourcp tells the main energy source of the household. It comes from another table (depmen and not menage) so we import the variable and merge it to the rest.

**Comment by benjello** [comment]
So we need to keep it.

**Comment by thomasdouenne** [comment]
Yes it is useful
