### ISSUE TITLE
How to get additional elements of legislation

### ISSUE THREAD

**Issue by thomasdouenne** [openfisca/openfisca-france-indirect-taxation#150]
On branch energie-migration, from a script such as one of those in examples/dataframes_from_legislation :

Previously we could use "tax_benefit_system.legislation_json" to get excises taxes from TICPE and other parameters from legislation. Now, "tax_benefit_system.legislation_json" raises the following error message : 

AttributeError: 'FranceIndirectTaxationTaxBenefitSystem' object has no attribute 'legislation_json'

Any idea of what is going wrong ?

**Comment by benjello** [comment]
Try something like 
````
legislation_json = tax_benefit_system.get_legislation_json()
````

**Comment by thomasdouenne** [comment]
The exact formula is :

from openfisca_france_indirect_taxation import FranceIndirectTaxationTaxBenefitSystem
tax_benefit_system = FranceIndirectTaxationTaxBenefitSystem()
legislation_json = tax_benefit_system.get_legislation()
