### ISSUE TITLE
How to link expenditure data to model variables in survey scenarios ?

### ISSUE THREAD

**Issue by thomasdouenne** [openfisca/openfisca-france-indirect-taxation#151]
When creating a dataframe using SurveyScenario, the variables decsribing households expenditures by good (such as 'poste_07_2_2_1_1' for gasoline, or 'depenses_ht_vin') return only 0. Other variables such as rev_disp_loyerimput work well, but consumption variables do not.

It seems that these variables that have a new name are not matched with BdF data. Any idea about how to make the right association between model and data ?

**Comment by thomasdouenne** [comment]
When trying to create a survey scenario with consumption data such as poste_coicop_07_2_2_1_1, when calling the variable we get :

KeyError: 'poste_coicop_07_2_2_1_1'

Is there another way to call them? Is there another structure for their name?

**Comment by thomasdouenne** [comment]
poste_07_2_2_1_1 is the right syntax

**Comment by benjello** [comment]
@thomasdouenne : you need to read [this] (https://github.com/openfisca/openfisca-france-indirect-taxation/blob/master/docs/data.md) and improve it ! ;-)
