### ISSUE TITLE
How to use a YearlyVariable in survey scenario ?

### ISSUE THREAD

**Issue by thomasdouenne** [openfisca/openfisca-france-indirect-taxation#153]
Some gasoline taxes do not apply before 2009, others not after 2007. If we call "essence_ticpe" it gives only Nan because some of its components give Nan for the year of the simulation. How to deal with the period of these variables ? This used to be handled by DatedVariables.

**Comment by benjello** [comment]
The DatedVariable do not exist anymore: use new [formula syntax](http://openfisca.org/doc/coding-the-legislation/40_legislation_evolutions.html)

**Comment by benjello** [comment]
@thomasdouenne : close when done ;-)

**Comment by thomasdouenne** [comment]
I must adapt the functions to this new structure.

However, there are other problems due to some price parameters of gasoline. super_95_e10_ttc gives only Nan while it shouldn't, and super_plombe_ttc gives values while it shouldn't (does not exist after 2007).

Do you know if something was changed in a file with respect to this ?

**Comment by benjello** [comment]
You should add an end attribute like written in the doc for `super_plombe_ttc`.
I do not know about `param\preprocessing.py` but you can add some debug information 
using `log.debug('balab')` to see if it is runned.

**Comment by thomasdouenne** [comment]
param\preprocessing.py is read, but the periods within that script are not: for each parameter, simulation.legislation_at(period.start)... takes the first value (the one of the first period). For the parameters that are directly taken from parameters.xml there is no such problem.

Should I change completely param\preprocessing.py to adopt a new form as described in the doc? Do you have an example that I could follow?

**Comment by benjello** [comment]
Yes.
I think you just have to change `legislation_at(period.start)` with legislation `legislation(period.start)` everywhere in the code.

**Comment by thomasdouenne** [comment]
When doing this I get the following error:

AttributeError: 'Simulation' object has no attribute 'legislation'

**Comment by benjello** [comment]
My error.
Let us work in analogy with openfisca-france (master branch)
Look at this [script] (https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py) called by this [one] (https://github.com/openfisca/openfisca-france/blob/cb273820523149cffad300ff851c7105f5922ba5/openfisca_france/france_taxbenefitsystem.py)

And the use the syntax of [formula_2017] (http://openfisca.org/doc/coding-the-legislation/40_legislation_evolutions.html) in th docs

**Comment by thomasdouenne** [comment]
We had to erase the "stop" and rank periods in the tree from the most recent to the oldest one
