### ISSUE TITLE
Cannot find electricity consumption

### ISSUE THREAD

**Issue by thomasdouenne** [openfisca/openfisca-france-indirect-taxation#154]
Officially the code is 04.5.1, I tried many possible combinaitions but keep having key errors. For other energies (gas, solid fioul, etc.) I have no problem with the standard syntax (ex : 04_5_2_1_1 for gas).

Is there a way to display all the poste recognized by the model ?

**Comment by benjello** [comment]
Try something looking at the keys of the following dictionary (or similar)
`survey_scenario.tax_benefit_system.columns_by_name`

**Comment by thomasdouenne** [comment]
Electricity corresponds to two variables :
- poste_04_5_1_1_1_a
- poste_04_5_1_1_1_b
I still need to understand what is the difference between the two

**Comment by thomasdouenne** [comment]
poste_04_5_1_1_1_a : expenditures in gas or electricity (not differentiated on the bill)
poste_04_5_1_1_1_b : expenditures in electricity (when differentiated on the bill)
