### ISSUE TITLE
Build_data for 2011 only

### ISSUE THREAD

**Issue by thomasdouenne** [openfisca/openfisca-france-indirect-taxation#155]
The script that builds consumption data (step_1_1_homogeneisation_donnees_depenses) is designed for 2011 only. When running the run_all for 2000 and 2005, consumption variables are still called poste_coicop_xxx (instead of poste_x_x_x).

We need to generalize it to include 2000 and 2005.

**Comment by thomasdouenne** [comment]
When applying to 2000 the function that translates variable names, it works. We need to check everything is done correctly.
When applying it to 2005, it raises an error. 'c05316' is missing from the survey data

**Comment by benjello** [comment]
There might be a typo in the survey.
You should investigate more upstream

**Comment by thomasdouenne** [comment]
There is a variable c05316 in the file Matrice passage 2005-COICOP.csv that is used to match variable names with those in BdF, but this variable is absent from BdF. This raises an assertion error.
I seems Matrice passage 2005-COICOP.csv is not automatically generated but was copied, so should I directly erase this variable from the file?

**Comment by benjello** [comment]
No erase the variable just after reading the csv file

**Comment by thomasdouenne** [comment]
Ok
