### ISSUE TITLE
Inflators do not work in survey scenarios

### ISSUE THREAD

**Issue by thomasdouenne** [openfisca/openfisca-france-indirect-taxation#156]
When using inflators to create a survey scenario we get the following error:

AttributeError: 'NoneType' object has no attribute 'unit'

so the structure of the inflators probably do not match the function that uses them in these scenario. Any idea to solve this?

**Comment by benjello** [comment]
@thomasdouenne : didn't you solve this already ?

**Comment by thomasdouenne** [comment]
No, not yet I was stucked on this.

**Comment by benjello** [comment]
Please indiciate the example you run.

**Comment by thomasdouenne** [comment]
You get the error if you run the script examples/master_thesis/energy_expenditures_by_category.py using the inflators to create survey_scenario

**Comment by benjello** [comment]
Try to update you api_migration branch and the openfisca-survey-manager repo too (api_migration branch).
The code runs but I am not sure that the reuslt is correct.

**Comment by thomasdouenne** [comment]
It seems correct at first glance, but I will create a test to make sure, thank you!
