### ISSUE TITLE
'SurveyScenario' object has no attribute 'create_data_frame_by_entity_key_plural'

### ISSUE THREAD

**Issue by thomasdouenne** [openfisca/openfisca-france-indirect-taxation#158]
When I try to create a dataframe at the individual level using:
df = = survey_scenario.create_data_frame_by_entity_key_plural(simulated_variables)

It raises the following error:
AttributeError: 'SurveyScenario' object has no attribute 'create_data_frame_by_entity_key_plural'

Do you know what is the new/correct way to write?

**Comment by benjello** [comment]
Use `create_data_frame_by_entity`

**Comment by thomasdouenne** [comment]
This is the error that follows when using create_data_frame_by_entity:

  File "c:\users\t.douenne\github\openfisca-core\openfisca_core\holders.py", line 165, in compute_add
    if self.column.definition_period == YEAR and period.unit == periods.MONTH:

AttributeError: 'NoneType' object has no attribute 'unit'

**Comment by benjello** [comment]
You should add  a `period` argument to `create_data_frame_by_entity`
````python
df = create_data_frame_by_entity(variables, period = 2015)
````

**Comment by thomasdouenne** [comment]
It works, thanks!
