### ISSUE TITLE
Use loops when summing variables with similar names

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-indirect-taxation#92]
Like in [here] (https://github.com/openfisca/openfisca-france-indirect-taxation/blob/master/openfisca_france_indirect_taxation/model/consommation/consommation_menages.py#L221)

**Comment by cbenz** [comment]
I would take advantage of the Python `sum()` function which takes a generator:

```python
    def function(self, simulation, period):
        result = sum(
            simulation.calculate('coicop_{}'.format(idx), period)
            for idx in xrange(1, 9)
            )
```

`sum()` uses the `+` operator which is overloaded by numpy so it's OK.

**Comment by benjello** [comment]
You are not assigned @cbenz !
This is an exercise for wana be coder economists ;-)
